# Use Node.js as the base image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the port that the app runs on
EXPOSE 3000

# Define the command to run the development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]