services:
  robotics-backend:
    container_name: robotics-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - ENVIRONMENT=development
      - PORT=8000
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - robotics-network

  robotics-frontend:
    container_name: robotics-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3002:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - ENVIRONMENT=development
      - VITE_API_BASE_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - robotics-backend
    restart: unless-stopped
    networks:
      - robotics-network

networks:
  robotics-network: